# boolean indexing
suppose we have an array (names) and another array(data) and the names in the array corresponds to rows in array

In [2]:
import numpy as np

In [2]:
name = np.array(['barun','asna','apurbha','barun','maskey','asna','krishna'])

In [9]:
datas = np.random.randn(7,5) # generataes a random array of matrixes
datas

array([[-1.23744094, -1.45059127,  1.6026385 ,  0.54705223, -0.51258379],
       [-1.1023418 , -0.48148849, -0.06021423,  0.21315337,  0.40443663],
       [ 0.50144319,  1.09095739,  0.81722492, -1.27045827, -0.55204312],
       [ 0.08456317, -0.93860286, -0.52728491,  0.61008722,  0.83036032],
       [ 0.45781823, -0.38733633,  0.29056722, -1.80524955, -0.80476686],
       [-1.58283226, -0.57237788,  2.76416878,  0.61601429,  0.88947968],
       [-1.76334264, -0.06431913, -0.34906945,  1.42846873,  0.24441365]])

In [11]:
datas[name == 'barun']

array([[-1.23744094, -1.45059127,  1.6026385 ,  0.54705223, -0.51258379],
       [ 0.08456317, -0.93860286, -0.52728491,  0.61008722,  0.83036032]])

In [12]:
name == 'barun' # returns an array of boolean
# these operations are vectorized..that is all of them are performed at a time ..no need of looping

array([ True, False, False,  True, False, False, False])

In [14]:
datas[~(name == 'barun')] #shows rows other than barun

array([[-1.1023418 , -0.48148849, -0.06021423,  0.21315337,  0.40443663],
       [ 0.50144319,  1.09095739,  0.81722492, -1.27045827, -0.55204312],
       [ 0.45781823, -0.38733633,  0.29056722, -1.80524955, -0.80476686],
       [-1.58283226, -0.57237788,  2.76416878,  0.61601429,  0.88947968],
       [-1.76334264, -0.06431913, -0.34906945,  1.42846873,  0.24441365]])

In [19]:
data = np.random.randn(6,6)
newData = data.copy()

data

array([[ 1.12944311, -0.07675491,  0.12208455, -1.92123162, -1.49900115,
        -0.23979171],
       [ 0.5134553 ,  0.07389547, -0.91901629, -0.2333578 ,  0.13283125,
        -0.47076753],
       [ 0.41772439,  1.13577823,  0.51248843,  0.81848623,  0.2293334 ,
        -0.00821799],
       [ 0.95428237, -1.52967588,  1.24004056,  1.06708445,  0.51722588,
        -0.83008241],
       [-0.5182377 , -0.54507827, -0.96093743, -0.3296642 ,  0.27833315,
        -0.59402986],
       [ 0.48410882,  0.39954669,  0.17325186, -0.98075552,  1.50385568,
        -0.75805311]])

In [23]:
data [data < 0] = 0
data

array([[1.12944311, 0.        , 0.12208455, 0.        , 0.        ,
        0.        ],
       [0.5134553 , 0.07389547, 0.        , 0.        , 0.13283125,
        0.        ],
       [0.41772439, 1.13577823, 0.51248843, 0.81848623, 0.2293334 ,
        0.        ],
       [0.95428237, 0.        , 1.24004056, 1.06708445, 0.51722588,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.27833315,
        0.        ],
       [0.48410882, 0.39954669, 0.17325186, 0.        , 1.50385568,
        0.        ]])

#fancy Indexing

In [32]:
fancyData = np.empty((8,3))
for x in range(8):
    fancyData [x] = x
fancyData

array([[0., 0., 0.],
       [1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.],
       [4., 4., 4.],
       [5., 5., 5.],
       [6., 6., 6.],
       [7., 7., 7.]])

we can easilt select multiple rows using list of indexes....#fancy 

In [33]:
fancyData[[1,2,3]]

array([[1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

now a werid phenomenon

In [38]:
fancyData[[1,5,3],[2,0,1]]

array([1., 5., 3.])

(here we got the result of (1,2),(5,2),(3,2))

this is bit unsual because we wanted to print row 1 in order of 3,1,2
lets do that

In [39]:
newFancyData = np.arange(32).reshape(8,4) # here we used reshape to reshape a ndarray into new narray of different dimensions
newFancyData

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [40]:
newFancyData[[1,5,3],[2,0,1]] # same problem as previous

array([ 6, 20, 13])

In [44]:
newFancyData[[1,5,3,2]][:,[3,2,0,1]]

array([[ 7,  6,  4,  5],
       [23, 22, 20, 21],
       [15, 14, 12, 13],
       [11, 10,  8,  9]])

another way of doing it is: using np.ix_() method

In [45]:
newFancyData[np.ix_([1,5,3,2],[3,2,0,1])]

array([[ 7,  6,  4,  5],
       [23, 22, 20, 21],
       [15, 14, 12, 13],
       [11, 10,  8,  9]])

#transposing a matrix

In [6]:
import numpy as np
newArray = np.arange(8).reshape(4,2)
newArray

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [9]:
newArray.transpose() 

array([[0, 2, 4, 6],
       [1, 3, 5, 7]])

In [10]:
newArray.T

array([[0, 2, 4, 6],
       [1, 3, 5, 7]])