#Indexing and Slicing

In [2]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5,6])

In [5]:
arr[2] #we can index ndarrays just like normal arrays

3

In [9]:
print(arr[2:])  # we can slice it too

[3 4 5 6]


In [10]:
arr[3:] = 9 #we can also asssign multiple values to arrays
arr

array([1, 2, 3, 9, 9, 9])

In [13]:
arr[:] = 8
arr

array([8, 8, 8, 8, 8, 8])

In [15]:
arr = np.array([1,2,3,4,5,6])

#for two diemnsional ararys

In [23]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [18]:
arr2d[0]

[1, 2, 3]

In [22]:
arr2d[1][2]

6

In [24]:
arr2d[0] = 1
print(arr2d)

[[1 1 1]
 [4 5 6]
 [7 8 9]]


In [35]:
print(arr2d[1][:2]) #these two are the same
print(arr2d[1,:2])

[4 5]
[4 5]


slicign items o all dimensions

In [36]:
print(arr2d[:,:1])

[[1]
 [4]
 [7]]


here we printed the first element of all dimension
