# Simultaing the power of ndarray with Random walks

The pure python approach

In [38]:
import time
start_time = time.time()
import random
steps = 100000
position = 0
draws = [position]
walk=[0]
for _ in range(steps):
    step = 1 if random.randint(0,1) else -1
    position += step
    walk.append(position)
    draws.append(step)
#print(walk)
print("--- %s seconds ---" % (time.time() - start_time))

--- 0.12574172019958496 seconds ---


Here we can do these with ndarrays as the draw are just random and doesnt depend on previous values

In [37]:
import time
start_time = time.time()
import numpy as np
draw = np.random.randint(0,2,size = 1000000)
steps = np.where(draw > 0 , 1, -1)
print(steps.cumsum())
print("--- %s seconds ---" % (time.time() - start_time))

[ -1   0   1 ... 634 633 632]
--- 0.01578497886657715 seconds ---


here we used numpy as an better alternative to problem of random walk..as the size increases...numpy does a better job at performing operation

W can also simulate many random walks at once with simple modifications

In [40]:
draw = np.random.randint(0,2,size =(100,500))
steps = np.where(draw > 0 , 1, -1)
print(steps)
print(steps.cumsum(1))

[[-1 -1  1 ...  1  1 -1]
 [ 1  1 -1 ... -1 -1 -1]
 [ 1 -1  1 ...  1  1  1]
 ...
 [ 1 -1 -1 ...  1  1  1]
 [ 1  1  1 ... -1  1  1]
 [-1 -1 -1 ... -1  1 -1]]
[[ -1  -2  -1 ... -18 -17 -18]
 [  1   2   1 ... -18 -19 -20]
 [  1   0   1 ...  20  21  22]
 ...
 [  1   0  -1 ...  -4  -3  -2]
 [  1   2   3 ...  26  27  28]
 [ -1  -2  -3 ...   4   5   4]]
