# Boolean Methods

In [1]:
import numpy as np

In [2]:
array1 = np.random.randn(50)
array1

array([ 1.36966412,  2.18886066, -0.41574227,  0.43375761,  1.80908373,
       -0.84566817, -2.4999028 ,  0.85774732,  0.05564588, -0.78316661,
       -0.45660098, -0.21173606, -0.70096973, -0.8544382 ,  0.23570015,
       -0.68287721, -0.73959939,  0.36594021, -0.47947362,  0.14945002,
        1.53122308, -0.08321072, -1.46954874,  0.13311921, -0.67794099,
       -2.8809737 ,  0.21508119,  0.13560572, -0.93765815, -1.24393153,
       -0.09436509, -1.26353627,  0.54383876,  0.90074274, -0.33644281,
       -0.0572624 , -0.0115865 ,  1.08449539, -0.44787579,  0.44560842,
       -0.19692919,  0.94043823,  0.10531713, -2.13997912, -1.35241594,
        1.19893419, -0.2847001 ,  0.25095649, -0.60878105,  0.52501214])

In [3]:
array1>0

array([ True,  True, False,  True,  True, False, False,  True,  True,
       False, False, False, False, False,  True, False, False,  True,
       False,  True,  True, False, False,  True, False, False,  True,
        True, False, False, False, False,  True,  True, False, False,
       False,  True, False,  True, False,  True,  True, False, False,
        True, False,  True, False,  True])

In [4]:
(array1 > 0).sum() 

22

that is there are 22 greater than 2 values

sum(array, axis, dtype, out, keepdims, initial)

In [5]:
(array1 > 0).any() # checks if any value of ndarray is true

True

In [6]:
(array1 > 0).all() #checks if all value of ndarray is true

False

We can also sort array just like lists using sort

In [9]:
array2 = np.array([1,2,3,-1,-6,9,0])
array2

array([ 1,  2,  3, -1, -6,  9,  0])

In [12]:
array2.sort()
array2

array([-6, -1,  0,  1,  2,  3,  9])

Multidimensional arrays can have each 1D section of values sorted in-place along an
axis by passing the axis number to sort :

In [35]:
arrayMd = np.random.randn(5,5)
arrayMd

array([[ 1.40236578,  0.16059791,  0.98071208,  1.86375508,  0.63775444],
       [ 1.54872788, -1.22004067, -1.24717584, -0.80169058,  2.19761891],
       [-0.84311905,  0.03124841, -1.79862105, -2.22106046,  0.27800633],
       [ 1.01600926,  0.79499984,  0.69696196, -0.05247131, -1.49198465],
       [-1.53120455,  0.50366008,  0.57296333,  1.58221715, -0.45399854]])

In [36]:
arrayMd.sort(axis = 0) #sort along x axis
arrayMd

array([[-1.53120455, -1.22004067, -1.79862105, -2.22106046, -1.49198465],
       [-0.84311905,  0.03124841, -1.24717584, -0.80169058, -0.45399854],
       [ 1.01600926,  0.16059791,  0.57296333, -0.05247131,  0.27800633],
       [ 1.40236578,  0.50366008,  0.69696196,  1.58221715,  0.63775444],
       [ 1.54872788,  0.79499984,  0.98071208,  1.86375508,  2.19761891]])

In [37]:
arrayMd.sort(axis = 1) #sort along x axis
arrayMd

array([[-2.22106046, -1.79862105, -1.53120455, -1.49198465, -1.22004067],
       [-1.24717584, -0.84311905, -0.80169058, -0.45399854,  0.03124841],
       [-0.05247131,  0.16059791,  0.27800633,  0.57296333,  1.01600926],
       [ 0.50366008,  0.63775444,  0.69696196,  1.40236578,  1.58221715],
       [ 0.79499984,  0.98071208,  1.54872788,  1.86375508,  2.19761891]])

# Unique and Other Set Logic

In [30]:
arrayDouble = np.array([1,2,3,4,1,2,5,3,8]) # here certain numbers are realated

In [38]:
np.unique(arrayDouble) # returns an array with no dublicate values and sorts is automatically

array([1, 2, 3, 4, 5, 8])

Another function, np.in1d , tests membership of the values in one array in another,
returning a boolean array:

In [39]:
np.in1d(arrayDouble,[1,2]) 

array([ True,  True, False, False,  True,  True, False, False, False])

#returns true if the given value is in the position of correesponding array

# File Input and Output with Arrays

np.save and np.load are used to store arrays. They are stored as .npy file

In [4]:
import numpy as np
arrayToSave = np.arange(16).reshape(4,4)
arrayToSave

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [5]:
np.save('herearray',arrayToSave)

In [7]:
np.load('herearray.npy')

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [8]:
np.savez('newarray',a = arrayToSave)

In [12]:
retDict = np.load('newarray.npz') 
retDict['a']

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

You save multiple arrays in a zip archive using np.savez and passing the arrays as key-
word arguments. When loading an .npz file, you get back a dict-like object which loads the individual
arrays lazily.
