#universal functions

In [1]:
import numpy as np

In [4]:
testArray = np.arange(16).reshape(4,4)
testArray

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

Elementwise opeariotns such as sqrt() and exp()

In [6]:
np.sqrt(testArray)

array([[0.        , 1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974, 2.64575131],
       [2.82842712, 3.        , 3.16227766, 3.31662479],
       [3.46410162, 3.60555128, 3.74165739, 3.87298335]])

In [7]:
np.exp(testArray)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04],
       [1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06]])

In [12]:
x = np.random.randn(8)
y = np.random.randn(8)
np.fmax(x,y)

array([ 0.14504737, -1.16182409,  1.41785381, -0.17404541,  0.99088253,
        2.47299935, -0.56398114, -0.67407306])

In [13]:
np.fmin(x,y)

array([-0.02839764, -1.24542565,  0.09530058, -1.04060205,  0.03338027,
       -0.29741728, -0.86519132, -1.5187905 ])

we have uniray(which perform operations on one matrix) and binary operations(performs of more than one matrixes)