In [1]:
import numpy as np

we have a txt file with numbers like in array

0.580052,0.186730,1.040717,1.134411
0.194163,-0.636917,-0.938659,0.124094
-0.126410,0.268607,-0.695724,0.047428
-1.484413,0.004176,-0.744203,0.005487
2.302869,0.200131,1.670238,-1.881090
-0.193230,1.047233,0.482803,0.960334

to convert this into a 2d ndarray, we use np.loadtxt

In [9]:
np.loadtxt('arrayList.txt',delimiter= ',')

array([[ 0.580052,  0.18673 ,  1.040717,  1.134411],
       [ 0.194163, -0.636917, -0.938659,  0.124094],
       [-0.12641 ,  0.268607, -0.695724,  0.047428],
       [-1.484413,  0.004176, -0.744203,  0.005487],
       [ 2.302869,  0.200131,  1.670238, -1.88109 ],
       [-0.19323 ,  1.047233,  0.482803,  0.960334]])

# Linear Algebra

- The Dot product

In [12]:
array1 = np.random.randn(2,2)
array1

array([[-1.62715469,  1.60496549],
       [ 1.84259165, -0.95059142]])

In [13]:
array2 = np.random.randn(2,2)
array2

array([[ 0.95838506, -1.13618291],
       [ 0.56541581,  1.29948065]])

In [14]:
np.dot(array1,array2) # matrix multiplication

array([[-0.65196789,  3.93436695],
       [ 1.22843289, -3.32879631]])

- numpy.linalg has a standard set of matrix decompositions and things like inverse and
determinant.
Table 4-7. Commonly-used numpy.linalg functions
Function Description
- diag Return the diagonal (or off-diagonal) elements of a square matrix as a 1D array, or convert a 1D array into a square matrix with zeros on the off-diagonal-
- dot Matrix multiplication
- trace Compute the sum of the diagonal elements
- det Compute the matrix determinant
- eig Compute the eigenvalues and eigenvectors of a square matrix
- inv Compute the inverse of a square matrix
- pinv Compute the Moore-Penrose pseudo-inverse inverse of a square matrix
- qr Compute the QR decomposition
- svd Compute the singular value decomposition (SVD)
- solve Solve the linear system Ax = b for x, where A is a square matrix
- lstsq Compute the least-squares solution to y = Xb

In [21]:
from numpy.linalg import *

In [22]:
dummyArray = np.random.randn(3,3)
dummyArray

array([[-0.10004654,  0.97296055, -1.16434837],
       [-1.63541283, -1.77755024, -0.18952761],
       [-0.15359963, -0.39659018,  0.62365439]])

In [27]:
inv(dummyArray) # inverse of  ndArray

array([[-1.68665615, -0.20663477, -3.21174414],
       [ 1.49473146, -0.34372823,  2.68617071],
       [ 0.53511378, -0.2694734 ,  2.52060473]])

In [28]:
np.trace(dummyArray) # trace need np. before it

-1.2539423895702853