In [11]:
import numpy as np
test1 = [1,2,3,4,5]
test2 = [6,7,8,9,10]

In [12]:
x , y = np.meshgrid(test1,test2)

In [13]:
print(np.sqrt(x*x+y*y)) # sqrt fins square root of final x^2+y^2..becaues its a matrix

[[ 6.08276253  6.32455532  6.70820393  7.21110255  7.81024968]
 [ 7.07106781  7.28010989  7.61577311  8.06225775  8.60232527]
 [ 8.06225775  8.24621125  8.54400375  8.94427191  9.43398113]
 [ 9.05538514  9.21954446  9.48683298  9.8488578  10.29563014]
 [10.04987562 10.19803903 10.44030651 10.77032961 11.18033989]]


The numpy.where function is a vectorized version of the ternary expression x if condi
tion else y.

In [14]:
test1 = [1,2,3,4,5]
test2 = [6,7,8,9,10]
mask = [True,False,True,True,False]

Suppose we wanted to take a value from xarr whenever the corresponding value in
cond is True otherwise take the value from yarr.
The normal way of doing it with python would be very tedious

In [15]:
print(np.where(mask,test1,test2))

[ 1  7  3  4 10]


heree if maske if true test1 is selectedted else test2 is selected

# what to do if you have two bolean masks

we can nest np.where like nested loops

In [47]:
test1 = [9,100,3,4,5]
test2 = [6,7,8,9,10]
test3 = [11,12,13,14,15]
test4 = [16,17,18,19,20]
mask1= [True,False,False,True,False]
mask2= [True,True,False,True,True]

In [50]:
np.where(np.array(mask2) * np.array(mask1), test1, np.where(mask1,test2,np.where(mask2,test3,test4)))

array([ 9, 12, 18,  4, 15])

#Mathematical statiscal methods


In [4]:
import numpy as np
dummyArray = np.random.randn(5,6)
dummyArray

array([[-0.33674859,  0.61161897,  0.32043602,  0.96649245, -0.0069705 ,
        -1.42529717],
       [-0.64608334, -1.76908611, -0.15995829,  1.44286076,  1.02490809,
        -0.22684274],
       [-1.1263515 ,  0.3284206 , -1.06996846,  0.0663863 , -1.97949492,
         0.07941843],
       [-1.13972143, -0.36318848, -1.06057231, -0.49870733, -1.35261105,
        -0.71023324],
       [ 0.30897579, -0.65969413, -2.20876571,  0.24500225,  0.67683846,
        -1.5790424 ]])

In [5]:
np.mean(dummyArray)

-0.40826598660347385

In [11]:
dummyArray.sum(axis = 1)

array([ 0.12953118, -0.33420163, -3.70158956, -5.12503385, -3.21668574])

In [15]:
a1 = np.arange(1,10,2)
a1

array([1, 3, 5, 7, 9])

Syntax : numpy.cumsum(arr, axis=None, dtype=None, out=None)

In [14]:
a1.cumsum() # 1,3+1,5+3+1

array([ 1,  4,  9, 16, 25])

we can also it on some axis if its multidimensional array...by default its fallttened array

In [17]:
a1 = np.arange(16).reshape(4,4)
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [18]:
a1. cumsum(0) # sums across y axis

array([[ 0,  1,  2,  3],
       [ 4,  6,  8, 10],
       [12, 15, 18, 21],
       [24, 28, 32, 36]])

In [19]:
a1.cumsum(1) #sums across x axis

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38],
       [12, 25, 39, 54]])

 numpy.cumprod(arr, axis=None, dtype=None, out=None)

In [21]:
#cum product
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [23]:
a1.cumprod(0)

array([[   0,    1,    2,    3],
       [   0,    5,   12,   21],
       [   0,   45,  120,  231],
       [   0,  585, 1680, 3465]])

In [24]:
a1.cumprod(1)

array([[    0,     0,     0,     0],
       [    4,    20,   120,   840],
       [    8,    72,   720,  7920],
       [   12,   156,  2184, 32760]])